# Generated by Django 4.2.7 on 2023-11-15 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_petpost_age_petpost_breed_petpost_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
